/* === LICENSE-HEADER START ===
This file is part of "portafolio-tailwind".
Code license: see LICENSE-CODE
Content license: see LICENSE-CONTENT
© 2025. See license files for full terms.
Generated by scripts/apply-license-headers.mjs
=== LICENSE-HEADER END === */

/**
 * Grade 3: Implementación de Portfolio Scroll con Tailwind + GSAP Modular
 * Refactorizado para integración con enrutador basado en hash
 *
 * Este módulo proporciona animaciones de desplazamiento y funcionalidad de navegación
 * que puede inicializarse cuando se monta una vista y limpiarse al navegar.
 */
import gsap from 'gsap';
import { ScrollToPlugin } from 'gsap/ScrollToPlugin';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

// Registrar plugins de GSAP una vez al cargar el módulo
gsap.registerPlugin(ScrollTrigger, ScrollToPlugin);

// ==========================================================================
// 1. Configuración
// ==========================================================================

const config = {
	reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)').matches,
	breakpoints: {
		sm: 640,
		md: 768,
		lg: 1024,
	},
};

// ==========================================================================
// 2. Módulo de Animación
// ==========================================================================

const animations = {
	/**
	 * Inicializar animaciones de GSAP dentro de un elemento contenedor
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de las animaciones
	 */
	init(container = document) {
		if (config.reducedMotion) {
			console.log('⚠️ Preferencia de movimiento reducido detectada — animaciones deshabilitadas');
			this.showAllElements(container);
			return;
		}

		this.initFadeUp(container);
		this.initParallax(container);
		this.initProjectCards(container);

		console.log('✨ Animations initialized');
	},

	/**
	 * Mostrar todos los elementos animados inmediatamente (para movimiento reducido)
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	showAllElements(container) {
		container.querySelectorAll('[data-animate]').forEach((el) => {
			el.style.opacity = '1';
			el.style.transform = 'none';
		});
	},

	/**
	 * Animaciones de desvanecimiento hacia arriba para elementos con data-animate="fade-up"
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	initFadeUp(container) {
		const elements = gsap.utils.toArray(container.querySelectorAll('[data-animate="fade-up"]'));

		elements.forEach((el) => {
			// Establecer estado inicial
			gsap.set(el, { opacity: 0, y: 40 });

			gsap.to(el, {
				opacity: 1,
				y: 0,
				duration: 0.8,
				ease: 'power2.out',
				scrollTrigger: {
					trigger: el,
					start: 'top 85%',
					toggleActions: 'play none none none',
				},
			});
		});
	},

	/**
	 * Efecto de paralaje para elementos con atributo data-parallax
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	initParallax(container) {
		const parallaxElements = container.querySelectorAll('[data-parallax]');

		parallaxElements.forEach((el) => {
			const speed = parseFloat(el.dataset.parallax) || 0.2;

			gsap.to(el, {
				yPercent: -100 * speed,
				ease: 'none',
				scrollTrigger: {
					trigger: el.parentElement,
					start: 'top bottom',
					end: 'bottom top',
					scrub: true,
				},
			});
		});
	},

	/**
	 * Revelación escalonada para tarjetas de proyecto
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	initProjectCards(container) {
		// Establecer estado inicial explícitamente para una posición de inicio consistente
		const cards = gsap.utils.toArray(container.querySelectorAll('.project-card'));
		gsap.set(cards, { y: 50, opacity: 0 });

		ScrollTrigger.batch(container.querySelectorAll('.project-card'), {
			onEnter: (batch) => {
				gsap.to(batch, {
					y: 0,
					opacity: 1,
					duration: 0.7,
					stagger: 0.12,
					ease: 'power2.out',
				});
			},
			start: 'top 90%',
			once: true,
		});
	},

	/**
	 * Limpiar todas las instancias de ScrollTrigger y animaciones
	 */
	destroy() {
		ScrollTrigger.getAll().forEach((trigger) => trigger.kill());
		gsap.killTweensOf('*');
	},
};

// ==========================================================================
// 3. Módulo de Navegación
// ==========================================================================

const navigation = {
	navbar: null,
	mobileMenuBtn: null,
	mobileMenu: null,
	scrollIndicator: null,
	eventListeners: [],
	initialized: false,

	/**
	 * Inicializar características de navegación dentro de un contenedor
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	init(container = document) {
		// La barra de navegación está en el documento principal, no en el contenedor
		this.navbar = document.getElementById('navbar');
		this.mobileMenuBtn = document.getElementById('mobile-menu-btn');
		this.mobileMenu = document.getElementById('mobile-menu');
		this.menuOverlay = document.getElementById('menu-overlay');
		this.menuIcon = document.getElementById('menu-icon');
		this.closeIcon = document.getElementById('close-icon');
		this.scrollIndicator = container.querySelector('.scroll-indicator');
		this.homeToggle = document.getElementById('home-toggle');
		this.homeSectionsMenu = document.getElementById('home-sections-menu');

		// El menú ahora se inicializa mediante el script inline en index.html para evitar conflictos
		// Inicializar funcionalidad del menú solo una vez (funciona en todas las rutas)
		if (!this.initialized) {
			this.initScrollBehavior();
			// this.initMobileMenu();  // DESHABILITADO - usando script inline en index.html
			// this.initHomeSectionsMenu();  // DESHABILITADO - usando script inline en index.html
			this.initialized = true;
		}

		// Solo inicializar características relacionadas con el desplazamiento si el contenedor tiene contenido de desplazamiento
		const hasScrollContent = container.querySelector('section[id]') || container.querySelector('.scroll-indicator');
		if (hasScrollContent) {
			this.initScrollIndicator(container);
			this.initSmoothScroll(container);
			this.initActiveState(container);
		} else {
			// Seguir manejando el desplazamiento suave para enlaces de sección incluso sin contenido de desplazamiento
			this.initSmoothScroll(container);
		}

		console.log('🧭 Navigation initialized');
	},

	/**
	 * Cambiar fondo de la barra de navegación al desplazarse
	 */
	initScrollBehavior() {
		if (!this.navbar) return;

		// La barra de navegación siempre es opaca, pero podemos agregar sombra al desplazarse para profundidad
		ScrollTrigger.create({
			start: 'top -100',
			onUpdate: (self) => {
				// Agregar sombra cuando se desplaza para profundidad visual
				if (self.scroll() > 100) {
					this.navbar.classList.add('shadow-lg');
					this.navbar.classList.remove('shadow-sm');
				} else {
					this.navbar.classList.remove('shadow-lg');
					this.navbar.classList.add('shadow-sm');
				}
			},
		});
	},

	/**
	 * Cerrar menú móvil (método auxiliar)
	 */
	closeMobileMenu() {
		if (!this.mobileMenu) return;
		this.mobileMenu.classList.add('hidden');
		this.menuOverlay?.classList.add('hidden');
		this.mobileMenuBtn?.setAttribute('aria-expanded', 'false');
		this.mobileMenu?.setAttribute('aria-hidden', 'true');
		this.menuOverlay?.setAttribute('aria-hidden', 'true');
		document.body.style.overflow = '';
		// Cerrar menús anidados
		if (this.homeSectionsMenu) {
			this.homeSectionsMenu.classList.add('hidden');
			this.homeToggle?.setAttribute('aria-expanded', 'false');
			const arrow = this.homeToggle?.querySelector('svg');
			if (arrow) {
				arrow.style.transform = 'rotate(0deg)';
			}
		}
	},

	/**
	 * Alternar menú móvil con animación de deslizamiento
	 */
	initMobileMenu() {
		if (!this.mobileMenuBtn || !this.mobileMenu) return;

		// Verificar si ya está inicializado para evitar listeners duplicados
		if (this.mobileMenuBtn.dataset.initialized === 'true') return;
		this.mobileMenuBtn.dataset.initialized = 'true';

		const openMenu = () => {
			this.mobileMenu.classList.remove('hidden');
			this.menuOverlay?.classList.remove('hidden');
			this.mobileMenuBtn?.setAttribute('aria-expanded', 'true');
			this.mobileMenu?.setAttribute('aria-hidden', 'false');
			this.menuOverlay?.setAttribute('aria-hidden', 'false');
			document.body.style.overflow = 'hidden'; // Prevenir desplazamiento del cuerpo
		};

		const closeMenu = () => {
			this.mobileMenu.classList.add('hidden');
			this.menuOverlay?.classList.add('hidden');
			this.mobileMenuBtn?.setAttribute('aria-expanded', 'false');
			this.mobileMenu?.setAttribute('aria-hidden', 'true');
			this.menuOverlay?.setAttribute('aria-hidden', 'true');
			document.body.style.overflow = '';
			this.mobileMenuBtn?.focus();
		};

		const toggleHandler = () => {
			const isOpen = !this.mobileMenu.classList.contains('hidden');
			if (isOpen) {
				closeMenu();
			} else {
				openMenu();
			}
		};

		this.mobileMenuBtn.addEventListener('click', toggleHandler);
		this.eventListeners.push({ element: this.mobileMenuBtn, event: 'click', handler: toggleHandler });

		// Cerrar menú al hacer clic en la superposición
		if (this.menuOverlay) {
			this.menuOverlay.addEventListener('click', closeMenu);
			this.eventListeners.push({ element: this.menuOverlay, event: 'click', handler: closeMenu });
		}

		// Cerrar menú al hacer clic en enlaces del enrutador (no en enlaces de sección)
		this.mobileMenu.querySelectorAll('a[href^="#/"]').forEach((link) => {
			link.addEventListener('click', closeMenu);
			this.eventListeners.push({ element: link, event: 'click', handler: closeMenu });
		});

		// Cerrar menú al presionar la tecla Escape
		const escapeHandler = (e) => {
			if (e.key === 'Escape' && !this.mobileMenu.classList.contains('hidden')) {
				closeMenu();
			}
		};
		document.addEventListener('keydown', escapeHandler);
		this.eventListeners.push({ element: document, event: 'keydown', handler: escapeHandler });
	},

	/**
	 * Inicializar alternancia de submenú de secciones de inicio
	 */
	initHomeSectionsMenu() {
		if (!this.homeToggle || !this.homeSectionsMenu) return;

		// Verificar si ya está inicializado para evitar listeners duplicados
		if (this.homeToggle.dataset.initialized === 'true') return;
		this.homeToggle.dataset.initialized = 'true';

		const toggleHandler = (e) => {
			e.preventDefault();
			const isExpanded = this.homeToggle.getAttribute('aria-expanded') === 'true';
			const arrow = this.homeToggle.querySelector('svg');

			if (isExpanded) {
				this.homeSectionsMenu.classList.add('hidden');
				this.homeToggle.setAttribute('aria-expanded', 'false');
				if (arrow) {
					arrow.style.transform = 'rotate(0deg)';
				}
			} else {
				this.homeSectionsMenu.classList.remove('hidden');
				this.homeToggle.setAttribute('aria-expanded', 'true');
				if (arrow) {
					arrow.style.transform = 'rotate(90deg)';
				}
			}
		};

		this.homeToggle.addEventListener('click', toggleHandler);
		this.eventListeners.push({ element: this.homeToggle, event: 'click', handler: toggleHandler });

		// Cerrar submenú al hacer clic en un enlace de sección
		this.homeSectionsMenu.querySelectorAll('a').forEach((link) => {
			const closeHandler = () => {
				// No cerrar el menú principal, solo navegar
				// El menú principal se cerrará automáticamente al hacer clic en el enlace de sección
			};
			link.addEventListener('click', closeHandler);
			this.eventListeners.push({ element: link, event: 'click', handler: closeHandler });
		});
	},

	/**
	 * Hacer que el indicador de desplazamiento del héroe sea clickeable para desplazarse a la siguiente sección
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	initScrollIndicator(container) {
		if (!this.scrollIndicator) return;

		// Encontrar la siguiente sección después del héroe (intentar primero #about, luego #features, luego primera sección después del héroe)
		let nextSection = container.querySelector('#about') || container.querySelector('#features');
		if (!nextSection) {
			const hero = container.querySelector('#hero');
			if (hero) {
				const allSections = container.querySelectorAll('section[id]');
				const heroIndex = Array.from(allSections).indexOf(hero);
				if (heroIndex >= 0 && heroIndex < allSections.length - 1) {
					nextSection = allSections[heroIndex + 1];
				}
			}
		}
		if (!nextSection) return;

		// Hacerlo visualmente interactivo
		this.scrollIndicator.style.cursor = 'pointer';
		this.scrollIndicator.setAttribute('role', 'button');
		const sectionName = nextSection.id || 'siguiente sección';
		this.scrollIndicator.setAttribute('aria-label', `Desplazarse a la sección ${sectionName}`);
		this.scrollIndicator.setAttribute('tabindex', '0');

		/**
		 * Desplazarse a la siguiente sección usando GSAP ScrollToPlugin
		 */
		const scrollToNext = () => {
			// Considerar la altura de la barra de navegación principal
			const navHeight = this.navbar?.offsetHeight || 80;
			if (config.reducedMotion) {
				// Desplazamiento instantáneo para preferencia de movimiento reducido
				window.scrollTo({
					top: nextSection.offsetTop - navHeight,
					behavior: 'auto',
				});
			} else {
				gsap.to(window, {
					duration: 0.8,
					scrollTo: { y: nextSection, offsetY: navHeight },
					ease: 'power2.inOut',
				});
			}
		};

		// Manejar clic
		this.scrollIndicator.addEventListener('click', scrollToNext);
		this.eventListeners.push({ element: this.scrollIndicator, event: 'click', handler: scrollToNext });

		// Manejar teclado (Enter/Espacio) para accesibilidad
		const keyHandler = (e) => {
			if (e.key === 'Enter' || e.key === ' ') {
				e.preventDefault();
				scrollToNext();
			}
		};
		this.scrollIndicator.addEventListener('keydown', keyHandler);
		this.eventListeners.push({ element: this.scrollIndicator, event: 'keydown', handler: keyHandler });
	},

	/**
	 * Desplazamiento suave para enlaces de anclaje (tanto en contenedor como en enlaces de sección de barra de navegación)
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	initSmoothScroll(container) {
		// Manejar enlaces de navegación de sección en el menú
		document.querySelectorAll('.section-nav-link').forEach((anchor) => {
			const clickHandler = (e) => {
				const targetId = anchor.getAttribute('href');
				// Omitir enlaces del enrutador (#/) y anclajes vacíos
				if (targetId === '#' || targetId.startsWith('#/')) return;

				e.preventDefault();

				// Verificar si estamos en la ruta de inicio
				const currentRoute = window.location.hash.slice(1) || '/';
				const isHomeRoute = currentRoute === '/' || currentRoute.startsWith('/#');

				if (isHomeRoute) {
					// Ya estamos en la ruta de inicio - solo desplazarse a la sección
					const target = container.querySelector(targetId) || document.querySelector(targetId);
					if (target) {
						const navHeight = this.navbar?.offsetHeight || 80;

						if (config.reducedMotion) {
							window.scrollTo({
								top: target.offsetTop - navHeight,
								behavior: 'auto',
							});
						} else {
							gsap.to(window, {
								duration: 0.8,
								scrollTo: { y: target, offsetY: navHeight },
								ease: 'power2.inOut',
							});
						}

						// Actualizar URL para incluir sección
						history.pushState(null, '', `#/${targetId}`);
					}
				} else {
					// No estamos en la ruta de inicio - navegar a inicio primero, luego desplazarse
					// Usar formato: #/#section para que el enrutador pueda manejarlo
					window.location.hash = `#/${targetId}`;
				}

			// Cerrar menú móvil si está abierto
				this.closeMobileMenu();
			};

			anchor.addEventListener('click', clickHandler);
			this.eventListeners.push({ element: anchor, event: 'click', handler: clickHandler });
		});

		// Manejar enlaces de anclaje dentro del contenedor (como botones en la sección héroe)
		container.querySelectorAll('a[href^="#"]').forEach((anchor) => {
			// Omitir si ya fue manejado como section-nav-link
			if (anchor.classList.contains('section-nav-link')) return;

			const clickHandler = (e) => {
				const targetId = anchor.getAttribute('href');
				// Omitir enlaces del enrutador (#/) y anclajes vacíos
				if (targetId === '#' || targetId.startsWith('#/')) return;

				const target = container.querySelector(targetId) || document.querySelector(targetId);
				if (target) {
					e.preventDefault();

					// Considerar la altura de la barra de navegación principal
					const navHeight = this.navbar?.offsetHeight || 80;

					if (config.reducedMotion) {
						// Desplazamiento instantáneo para movimiento reducido
						window.scrollTo({
							top: target.offsetTop - navHeight,
							behavior: 'auto',
						});
					} else {
						gsap.to(window, {
							duration: 0.8,
							scrollTo: { y: target, offsetY: navHeight },
							ease: 'power2.inOut',
						});
					}

					// Actualizar hash de URL (pero no navegación completa)
					history.pushState(null, '', targetId);
				}
			};

			anchor.addEventListener('click', clickHandler);
			this.eventListeners.push({ element: anchor, event: 'click', handler: clickHandler });
		});
	},

	/**
	 * Enlace de navegación activo basado en la posición de desplazamiento
	 * @param {HTMLElement} container - El elemento contenedor para limitar el alcance de consultas
	 */
	initActiveState(container) {
		const sections = container.querySelectorAll('section[id]');
		const sectionNavLinks = container.querySelectorAll('.section-nav-link');
		const routerNavLinks = document.querySelectorAll('.nav-link[href^="#/"]');

		if (sections.length === 0) return;

		sections.forEach((section) => {
			ScrollTrigger.create({
				trigger: section,
				start: 'top center',
				end: 'bottom center',
				onEnter: () => this.setActiveSectionLink(section.id),
				onEnterBack: () => this.setActiveSectionLink(section.id),
			});
		});
	},

	setActiveSectionLink(sectionId) {
		// Update section navigation links (in dropdown)
		document.querySelectorAll('.section-nav-link').forEach((link) => {
			if (link.getAttribute('href') === `#${sectionId}`) {
				link.classList.add('text-primary', 'font-semibold');
				link.classList.remove('text-muted-foreground');
			} else {
				link.classList.remove('text-primary', 'font-semibold');
				link.classList.add('text-muted-foreground');
			}
		});
	},

	/**
	 * Limpiar listeners de eventos y restaurar desplazamiento del cuerpo
	 * Nota: La funcionalidad del menú se conserva entre rutas, solo se limpian las características de desplazamiento
	 */
	destroy() {
		// Solo limpiar listeners relacionados con el desplazamiento, no la funcionalidad del menú
		// El menú debe persistir entre rutas
		const scrollListeners = this.eventListeners.filter(
			({ element }) => element.classList?.contains('scroll-indicator') || element.classList?.contains('section-nav-link')
		);

		scrollListeners.forEach(({ element, event, handler }) => {
			element.removeEventListener(event, handler);
		});

		// Eliminar listeners de desplazamiento del array
		this.eventListeners = this.eventListeners.filter(
			({ element }) => !element.classList?.contains('scroll-indicator') && !element.classList?.contains('section-nav-link')
		);

		// Restaurar desplazamiento del cuerpo si el menú estaba abierto (pero no cerrar menú - debe persistir)
		document.body.style.overflow = '';
	},
};

// ==========================================================================
// 4. API Pública para Integración con Enrutador
// ==========================================================================

/**
 * Inicializar animaciones de desplazamiento y navegación para una vista
 * @param {HTMLElement} container - El elemento contenedor (típicamente el elemento app)
 */
export function initScrollView(container) {
	// Desplazarse al inicio cuando se carga la vista
	window.scrollTo({ top: 0, behavior: 'auto' });

	// Inicializar animaciones
	animations.init(container);

	// Inicializar navegación (menú se inicializa globalmente, pero características de desplazamiento son por vista)
	navigation.init(container);

	// Actualizar ScrollTrigger después de un pequeño retraso para asegurar que el DOM esté listo
	// y después de que las imágenes se carguen
	setTimeout(() => {
		ScrollTrigger.refresh();
	}, 100);

	window.addEventListener(
		'load',
		() => {
			ScrollTrigger.refresh();
		},
		{ once: true }
	);

	console.log('🚀 Scroll view initialized');
}

/**
 * Limpiar animaciones de desplazamiento y navegación al abandonar la vista
 */
export function cleanupScrollView() {
	animations.destroy();
	// No destruir navegación - debe persistir entre rutas
	// navigation.destroy();
	console.log('🧹 Vista de desplazamiento limpiada');
}

/**
 * Inicializar menú de navegación (debe llamarse una sola vez globalmente)
 */
export function initNavigation() {
	navigation.init(document);
	console.log('🧭 Menú de navegación inicializado');
}
/**
 * Inicializar funcionalidad de alternancia de vista de proyectos
 */
export function initProjectsToggle(container = document) {
	const gridBtn = container.getElementById ? container.getElementById('grid-view-btn') : container.querySelector('#grid-view-btn');
	const listBtn = container.getElementById ? container.getElementById('list-view-btn') : container.querySelector('#list-view-btn');
	const projectsGrid = container.getElementById ? container.getElementById('projects-grid') : container.querySelector('#projects-grid');

	if (!gridBtn || !listBtn || !projectsGrid) {
		return;
	}

	let isGridView = true;

	const updateButtonStyles = (active, inactive) => {
		active.classList.add('bg-white', 'dark:bg-gray-800', 'text-gray-900', 'dark:text-white', 'shadow-md');
		active.classList.remove('text-gray-600', 'dark:text-gray-400');
		
		inactive.classList.remove('bg-white', 'dark:bg-gray-800', 'text-gray-900', 'dark:text-white', 'shadow-md');
		inactive.classList.add('text-gray-600', 'dark:text-gray-400');
	};

	gridBtn.addEventListener('click', (e) => {
		e.preventDefault();
		if (isGridView) return;
		isGridView = true;
		
		projectsGrid.className = 'grid md:grid-cols-2 lg:grid-cols-3 gap-6';
		updateButtonStyles(gridBtn, listBtn);

		container.querySelectorAll('.project-card').forEach(card => {
			card.classList.remove('md:flex', 'gap-4', 'flex-col', 'md:flex-row');
		});
	});

	listBtn.addEventListener('click', (e) => {
		e.preventDefault();
		if (!isGridView) return;
		isGridView = false;
		
		projectsGrid.className = 'grid md:grid-cols-2 lg:grid-cols-2 gap-4';
		updateButtonStyles(listBtn, gridBtn);

		container.querySelectorAll('.project-card').forEach(card => {
			card.classList.add('md:flex', 'gap-4');
			card.classList.add('flex-col', 'md:flex-row');
		});
	});

	console.log('🎨 Alternancia de proyectos inicializada');
}